"""add default value

Revision ID: fa902b68342a
Revises: b9c4a1c19a0e
Create Date: 2022-11-12 20:03:06.268002

"""
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "fa902b68342a"
down_revision = "b9c4a1c19a0e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "order_history",
        "status",
        existing_type=mysql.VARCHAR(length=255),
        nullable=True,
        default="0",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "order_history",
        "status",
        existing_type=mysql.VARCHAR(length=255),
        nullable=False,
    )
    # ### end Alembic commands ###
