"""add table storage

Revision ID: f83467c792e1
Revises: fa902b68342a
Create Date: 2022-11-12 22:00:48.636458

"""
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f83467c792e1"
down_revision = "fa902b68342a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "storage",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="id"),
        sa.Column("goods_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("storage")
    # ### end Alembic commands ###
