"""add status for order_history

Revision ID: b9c4a1c19a0e
Revises: 742f81ba52e2
Create Date: 2022-11-12 20:01:10.421073

"""
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9c4a1c19a0e'
down_revision = '742f81ba52e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_history', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_history', 'status')
    # ### end Alembic commands ###
